### ISSUE TITLE
Armadillo configuration doesn't compile on UNICORN

### ISSUE THREAD

**Issue by S0S-90** [AKEngels/CAST#21]
After running premake5 ``make config=armadillo_release_x64`` throws errors and doesn't build CAST.

**Comment by schaerfo** [comment]
Sorry, my bad. When disabling the copy ctor of scon::mathmatrix, I accidentally also disabled the ctor taking an instance of the base class which apparently is needed for the Armadillo configuration.

**Comment by schaerfo** [comment]
Does the fix introduced in commit e23ba85cfe33ef9ceaa8dd9d0bfaaf48955b496d work?

**Comment by S0S-90** [comment]
Yes, it works. Thanks!

**Comment by schaerfo** [comment]
Ok, closing this issue then.
