### ISSUE TITLE
Tests of current devel branch fail on UNICORN

### ISSUE THREAD

**Issue by S0S-90** [AKEngels/CAST#22]
The following tests are currently failing on UNICORN:

[  FAILED  ] 6 tests, listed below:
[  FAILED  ] InternalCoordinatesTranslationXTest.returnInfoTest
[  FAILED  ] InternalCoordinatesTranslationYTest.returnInfoTest
[  FAILED  ] InternalCoordinatesTranslationZTest.returnInfoTest
[  FAILED  ] InternalCoordinatesRotationInfoTest.infoOfRotationA
[  FAILED  ] InternalCoordinatesRotationInfoTest.infoOfRotationB
[  FAILED  ] InternalCoordinatesRotationInfoTest.infoOfRotationC

**Comment by JulianEr** [comment]
Sorry, tests passed on Windows and Debian alike, thus they kept unnoticed. Found the bug and working on a fix. Unfortunately the bug seems to be involved pretty deep. Ignore them for now or uncomment them if you like. The bug only occurs in the tests. The production code is not affected.

**Comment by JulianEr** [comment]
Tests are now running. Closing Issue.
