### ISSUE TITLE
Linking with armadillo doesn't seem to work anymore

### ISSUE THREAD

**Issue by mrnicegyu11** [AKEngels/CAST#23]
Maybe the libopenblas.a found in CAST's optional files directory is outdated?

Error on ECPC for building:

`==== Building GoogleTest (armadillo_debug_x64) ====
==== Building CAST (armadillo_debug_x64) ====
Linking CAST
../linux_precompiled_libs/libopenblas.a(dgesvd.o): In function `dgesvd_':
dgesvd.f:(.text+0x421): undefined reference to `_gfortran_concat_string'
dgesvd.f:(.text+0xf1f): undefined reference to `_gfortran_concat_string'
../linux_precompiled_libs/libopenblas.a(dormbr.o): In function `dormbr_':
dormbr.f:(.text+0x3b9): undefined reference to `_gfortran_concat_string'
dormbr.f:(.text+0x627): undefined reference to `_gfortran_concat_string'
dormbr.f:(.text+0x6be): undefined reference to `_gfortran_concat_string'
../linux_precompiled_libs/libopenblas.a(dormbr.o):dormbr.f:(.text+0x736): more undefined references to `_gfortran_concat_string' follow
../linux_precompiled_libs/libopenblas.a(dlasd0.o): In function `dlasd0_':
dlasd0.f:(.text+0x7af): undefined reference to `_gfortran_pow_i4_i4'
../linux_precompiled_libs/libopenblas.a(dlasda.o): In function `dlasda_':
dlasda.f:(.text+0xec2): undefined reference to `_gfortran_pow_i4_i4'
dlasda.f:(.text+0x105f): undefined reference to `_gfortran_pow_i4_i4'
../linux_precompiled_libs/libopenblas.a(dstedc.o): In function `dstedc_':
dstedc.f:(.text+0x3d5): undefined reference to `_gfortran_pow_i4_i4'
dstedc.f:(.text+0x3f4): undefined reference to `_gfortran_pow_i4_i4'
../linux_precompiled_libs/libopenblas.a(ilaenv.o): In function `ilaenv_':
ilaenv.f:(.text+0xbc): undefined reference to `_gfortran_compare_string'
ilaenv.f:(.text+0xdd): undefined reference to `_gfortran_compare_string'
ilaenv.f:(.text+0xfe): undefined reference to `_gfortran_compare_string'
ilaenv.f:(.text+0x11f): undefined reference to `_gfortran_compare_string'
ilaenv.f:(.text+0x13c): undefined reference to `_gfortran_compare_string'
../linux_precompiled_libs/libopenblas.a(ilaenv.o):ilaenv.f:(.text+0x159): more undefined references to `_gfortran_compare_string' follow
../linux_precompiled_libs/libopenblas.a(dormtr.o): In function `dormtr_':
dormtr.f:(.text+0x32b): undefined reference to `_gfortran_concat_string'
dormtr.f:(.text+0x592): undefined reference to `_gfortran_concat_string'
dormtr.f:(.text+0x624): undefined reference to `_gfortran_concat_string'
dormtr.f:(.text+0x69c): undefined reference to `_gfortran_concat_string'
../linux_precompiled_libs/libopenblas.a(dlaed0.o): In function `dlaed0_':
dlaed0.f:(.text+0x37f): undefined reference to `_gfortran_pow_i4_i4'
dlaed0.f:(.text+0x392): undefined reference to `_gfortran_pow_i4_i4'
../linux_precompiled_libs/libopenblas.a(dlaed7.o): In function `dlaed7_':
dlaed7.f:(.text+0x1a9): undefined reference to `_gfortran_pow_i4_i4'
dlaed7.f:(.text+0x1de): undefined reference to `_gfortran_pow_i4_i4'
../linux_precompiled_libs/libopenblas.a(dlaeda.o): In function `dlaeda_':
dlaeda.f:(.text+0x7f): undefined reference to `_gfortran_pow_i4_i4'
../linux_precompiled_libs/libopenblas.a(dlaeda.o):dlaeda.f:(.text+0x8e): more undefined references to `_gfortran_pow_i4_i4' follow
../linux_precompiled_libs/libopenblas.a(dormql.o): In function `dormql_':
dormql.f:(.text+0x6c1): undefined reference to `_gfortran_concat_string'
dormql.f:(.text+0x80c): undefined reference to `_gfortran_concat_string'
collect2: error: ld returned 1 exit status
CAST.make:531: recipe for target '../build/CAST_linux_x64_armadillo_debug' failed
make[1]: *** [../build/CAST_linux_x64_armadillo_debug] Error 1
Makefile:90: recipe for target 'CAST' failed
make: *** [CAST] Error 2
`

**Comment by schaerfo** [comment]
Older versions of ld require the flags to be in a specific order, which were incorrectly specified in the premake.lua file. Commit 370059da should fix this.

**Comment by mrnicegyu11** [comment]
is fixed, thank you!
