### ISSUE TITLE
Problem with torsions in forcefield calculations

### ISSUE THREAD

**Issue by S0S-90** [AKEngels/CAST#24]
There seems to be a problem in finding torsion forcefield parameters. When doing a SP calculation with the OPLSAA forcefield I get more than 2000 warnings of the type:

``No torsion parameters (or parameters exactly equal to zero) found for [Number:1,2,3,4][Types: 230,236,177,178][Type/Class: 53,13,3,4]``  (number always different)

Furthermore the result differs from the one I got two months ago and it's only the energy of the torsions that is different to then.

**Comment by S0S-90** [comment]
The warnings seems to be independant of the change of the energy as with commit a2f71c0681e2493d9a24bd19d265afcb73a9c469 I also get those warnings but the energy is still the same as before.

**Comment by S0S-90** [comment]
When I put the changes made in commit a030456a4e525cca77ca4327fbe0991cc560766f into commit a2f71c0 the energy changes but it is still not identical to the one I get with the most recent commit.

**Comment by mrnicegyu11** [comment]
I'll look into it

**Comment by S0S-90** [comment]
I think I fixed this bug. Obviously it was necessary also to take into account the torsional interactions where all the parameters are zero. Now we also have the same number of torsional interactions as tinker (though the energy stills differs by around 2 kcal/mol but it is at least the same energy as 2 months ago).

**Comment by mrnicegyu11** [comment]
perfect, thank you!! :--)
