### ISSUE TITLE
Potential bug(?) in torsional refinement

### ISSUE THREAD

**Issue by mrnicegyu11** [AKEngels/CAST#25]
![image](https://user-images.githubusercontent.com/8209087/63859229-3d7f8700-c9a7-11e9-8315-9ae45d22eecb.png)

This code is still from the original CAST git commit. Notice the "else if" makes no sense. As this function checks if the torsion from the aprameter file matches the current atoms, it is maybe(!) supposed to be:
`else if (index[0] == d && index[1] == c && index[2] == b && index[3] == a) return 4u;`

but I am not sure?

**Comment by S0S-90** [comment]
Yes, I think this supposed to be as you suggested but I also think it doesn't matter because the last line also returns 4 if all the indices are identical.

**Comment by S0S-90** [comment]
changed it
