### ISSUE TITLE
current devel branch does not compile

### ISSUE THREAD

**Issue by S0S-90** [AKEngels/CAST#26]
The current devel branch is neither compiled on UNICORN nor on my windows machine.

On Linux it says:
``../../src/ic_exec.h:5:10: fatal error: graph.h: No such file or directory
 #include "graph.h"``

On Windows there are some more errors also in file ic_exec.h which say that file ic_util.h can't be opened (line 11) and that namespace "ic_util" doesn't have a member bonds (line 83).

**Comment by JulianEr** [comment]
Argh, darn renaming. Please switch to a former commit. I'll fix this as soon, as I am on my workstation again. (Or revert my commit if that costs less time and effort)

**Comment by JulianEr** [comment]
Solved, was a little bug in the Optimizer for TRIC additional to the renaming issues
