### ISSUE TITLE
Heap is corrupt

### ISSUE THREAD

**Issue by mrnicegyu11** [AKEngels/CAST#27]
On commit e95b6efb4b80bd984f8952a9f845207788f24c83 on my Windows PC there are heap assertion triggered (double free etc). Assertions occur reproducible. Reason is currently unknown.

**Comment by JulianEr** [comment]
Sounds like a runtime problem? When do you get the error? Tests run on my windows machine.

**Comment by S0S-90** [comment]
Did you try to delete everything else in your build folder? I remember that I had a problem once when I had a CAST.txt folder there. If the error doesn't appear then it would still be a bug but it would at least explain why the error only occurs on your machine.

**Comment by mrnicegyu11** [comment]
Happens when running tests, i'll try deleting the build folder thx

**Comment by mrnicegyu11** [comment]
valgrind on UNICORN says we are definately leaking memory, invesitgation ongoing
![image](https://user-images.githubusercontent.com/8209087/64066627-88ee9b00-cc1c-11e9-8e23-97c69de1b612.png)

**Comment by mrnicegyu11** [comment]
![image](https://user-images.githubusercontent.com/8209087/64066630-94da5d00-cc1c-11e9-83bc-f09b8f62ff18.png)

**Comment by mrnicegyu11** [comment]
Sorry to say this @JulianEr , but all memory leaks found by valgrind/valkyrie are inside of the internal-coordinate code (yours ;) ). So to the best of my current knowledge some internal-coordinates codes leaks memory, therefore forgets to free some variables. As for some weird buggy reason I am unable to export the log of valgrind, I'll tell you how to reproduce the memory-leak-report:
- Log on ECPC, clone & build CAST (testing build) on UNICORN
- run "valkyrie" in the ./optional_files/build/ folder, a GUI will pop up
- Under "edit>options" under "valkyrie options" set "binary" to the path of the CAST_testing executable (in my case: "/home/dustin/git/CAST/optional_files/build/CAST_linux_x64_testing")
- Close the settings windows, click on the "medieval knight icon" to run valgrind and get all the memory leaks in the GUI. 

Actually, gTest seems to use an unititialized variable but I am chosing to ignore this for now as there are more issues in CAST itself :D

Btw, here is an examplary call-stack of the object leaking memory: 
![image](https://user-images.githubusercontent.com/8209087/64066732-c0117c00-cc1d-11e9-9d47-944cdc196a8f.png)
Seems like std::make_unique causes trouble? 

Please check this out @JulianEr if you have a spare minute. If I can help, just tell me ;)

**Comment by JulianEr** [comment]
I'll look into this on monday. Strange that a unique pointer leaks memory. And there is no other memory allocation except the ones in smart pointer.

**Comment by JulianEr** [comment]
The issue was some non implemented virtual Destructors. There are still alleged errors left caused by Google Test. I guess they are false positives? Found this fix by quick googling and quick valgrinding: https://www.kullo.net/blog/why-valgrind-reports-uninitialised-value-errors-when-running-google-testmock/
But before "fixing" this I would rather wait until you tested this @mrnicegyu11. On my machines (Linux and Windows) it does neither crash nor report leaks. (except these maybe false positives)

**Comment by mrnicegyu11** [comment]
Works for me, no more heap issues on my windows PC at commit 18d34b9dedd870cc4ac9fd5759354afb6d59991f (linux worked for me anyway or didnt show any issues at least). So I'm good. If you wanna fix the googletest issues go ahead, I'd probably just ignore them, so I dont care :D THX for the effort and quick fix!!

**Comment by mrnicegyu11** [comment]
@JulianEr can this issue be closed? Seems resolved on my end ;)

**Comment by S0S-90** [comment]
I also get memory leaks when running the release configuration with the following minimal inputfile:
```verbosity              4
cores                  4
name                   butanol.arc
outname                output
inputtype              TINKER
task                   SP
interface              OPLSAA
paramfile              oplsaa.prm

cutoff                 12.0
switchdist             10.0
```

If I comment out the last two lines everything works fine. I'm playing around with valkyrie and try to find out a bit more.

**Comment by S0S-90** [comment]
The issue also happens with debug and testing configurations on Windows as well as on Linux. Valkyrie reports errors in different files but I don't see any connection with cutoff and switchdist:
![Unbenannt](https://user-images.githubusercontent.com/21076804/64793253-11edc680-d57b-11e9-8648-9d1531c8f143.png)

**Comment by mrnicegyu11** [comment]
The coords::Coordinates object "cobj" is seemingly not valid. Depending on the valgrind error you get, "cobj" might be an unitialized pointer in the first place or maybe it is not free'd after use. That is at least my best guess. Alternativly its an OpenMP Problem, so maybe try it with and wothout openmp (but dont just change the CAST.txt file but compile explicitly with and without openMP flags and ifdefs). Hope that helps

**Comment by S0S-90** [comment]
Ýes, it seems to be problem with openMP and the linked cell algorithmus. The problem only shows up because linked cell is only used when cutoff is smaller than 500 angstrom.

**Comment by S0S-90** [comment]
Just commented out the line with the openMP directive, now the program is working (with debug and testing). For the debug configuration however Valkyrie still shows memory leaks and they still can be backtraced to a line with openMP (```#pragma omp parallel sections```, energy_int_aco_pot.cc:56) which is called from main file (I guess that's why it doesn't show for testing configuration). So I assume we could get more errors of that kind in the future.

**Comment by mrnicegyu11** [comment]
I forgot what we did, but this seems fixed. If noone opposes I'll close the issue next week.
