### ISSUE TITLE
Visual Studio Debugger does not work

### ISSUE THREAD

**Issue by S0S-90** [AKEngels/CAST#32]
CAST currently does not compile within the Visual Studio Debugger. When trying this a windows appears saying: 

Das Programm "E:\GIT_Repositories\CAST\optional_files\project\libs\ALGLIB\..\..\..\libs\Debug\ALGLIB.lib" kann nicht gestartet werden.
"E:\GIT_Repositories\CAST\optional_files\project\libs\ALGLIB\..\..\..\libs\Debug\ALGLIB.lib" ist keine gültige Win32-Anwendung.

This happens in x32 as well as in x64 mode.

**Comment by mrnicegyu11** [comment]
@S0S-90 still relevant? Debugger works for me ;--)

**Comment by S0S-90** [comment]
For me it still does not work but breaks with the above error message.

**Comment by S0S-90** [comment]
It is possible to enter the debugger by right-clicking on "CAST" in the Projektmappen-Explorer and then choosing "Debuggen".

If clicking the button "Lokaler Windows Debugger" like I did before, Visual Studio tries to start Alglib and this causes the error described above.

Thanks to @MichelsBa for finding out :-)
